springdoc:
  show-actuator: true
spring:
  datasource:
    username: username
    password: password
    url: jdbc:h2:mem:jpadb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
